{% set name = "xeus-cling" %}
{% set version = "0.0.5" %}
{% set sha256 = "047d2028686524fa88e3e30026ea03ba637c948944840111d7ec32fac0aacdef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xeus-cling/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py<35]
  features:   # [win]
    - vc14    # [win]

requirements:
  build:
    - toolchain
    - cmake
    - cppzmq
    - zeromq
    - cryptopp
    - cling >=0.5,<0.6
    - xeus >=0.6.0,<0.7
    - xtl >=0.2.2,<0.3
    - pugixml
    - cxxopts
  run:
    - cppzmq             # Even though cppzmq is header-only, it is used at runtime by the interpreted c++
    - xtl  >=0.2.2,<0.3  # Even though xtl is header-only, it is used at runtime by the interpreted c++
    - xeus >=0.6.0,<0.7
    - zeromq
    - cryptopp
    - util-linux         # [linux]
    - cling  >=0.5,<0.6

test:
  commands:
    - test -f ${PREFIX}/bin/xeus-cling  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\xeus-cling.exe (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xeus
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Cling-based C++ kernel for Jupyter based on xeus'
  description: 'xeus is a library meant to facilitate the implementation of kernels for Jupyter. It takes the burden of implementing the Jupyter Kernel protocol so developers can focus on implementing the interpreter part of the Kernel.'
  doc_url: http://xeus.readthedocs.io
  dev_url: https://github.com/QuantStack/xeus

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
